version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_DATABASE: project_training
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@1234
      MYSQL_ROOT_PASSWORD: Root@2022
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./_data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080

# version: '3.1'

# services:
#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: Root@2022
#       MYSQL_DATABASE: collection-db
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: admin@1234
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - 3306:3306

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# volumes:
#   db_data:
